name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [deploy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make deploy script executable
        run: chmod +x scripts/deploy.sh

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Convert script line endings (Windows compatibility)
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix scripts/deploy.sh

      - name: Try SSH command on EC2
        run: |
          ssh -v -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'whoami; hostname; pwd'
      - name: Deploy via script
        run: |
          ssh -v -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'bash -s' < scripts/deploy.sh

